<?php

if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_550b61a478d61',
	'title' => 'Contact',
	'fields' => array (
		array (
			'key' => 'field_5567df7742ec8',
			'label' => 'Contact Type',
			'name' => 'contact_type',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => 'Choice your contact template type',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'contactstyle1' => 'Full width form 2 column map and detail',
				'contactstyle2' => 'Full width map 2 column form and detail',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'contactstyle1',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_5506ab8550ca6',
			'label' => 'Contact Maps iFrame',
			'name' => 'contact_maps_iframe',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => 'Embed a google maps iframe code here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_555c0f30ca85e',
			'label' => 'Telephone Number',
			'name' => 'telephone_number',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_555c0f46ca85f',
			'label' => 'Email Address',
			'name' => 'email_address',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_555c0f51ca860',
			'label' => 'Office Address',
			'name' => 'office_address',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_555c0f95c2883',
			'label' => 'Contact Template',
			'name' => 'contact_template',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'paste your contact forrm 7 template ID here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template/contact-template.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_555ee4ce4d307',
	'title' => 'Gallery Image',
	'fields' => array (
		array (
			'key' => 'field_555ee4da59f6d',
			'label' => 'Kedavra Gallery',
			'name' => 'kedavra_gallery',
			'prefix' => '',
			'type' => 'gallery',
			'instructions' => 'Insert your images as gallery here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'preview_size' => 'sow-carousel-default',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template/gallery-template.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_5562ac71b9d34',
	'title' => 'Page Option',
	'fields' => array (
		array (
			'key' => 'field_5562aca545300',
			'label' => 'Header Background Choice',
			'name' => 'header_background_choice',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => 'Select header background type for a statistic page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'transparent' => 'Transparent',
				'default' => 'Default header',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'default',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_55655c6aa377e',
			'label' => 'Header Color',
			'name' => 'header_color',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5562aca545300',
						'operator' => '==',
						'value' => 'default',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'light' => 'Light',
				'default' => 'Default',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'default',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_5562b198cf061',
			'label' => 'Hide Title',
			'name' => 'hide_title',
			'prefix' => '',
			'type' => 'true_false',
			'instructions' => 'Will not effected in single portfolio page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_5562d2f114913',
			'label' => 'Use Margin',
			'name' => 'use_margin',
			'prefix' => '',
			'type' => 'true_false',
			'instructions' => 'Will not effected in single portfolio page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
		),
		array (
			'key' => 'field_5562d28d14912',
			'label' => 'Add Margin',
			'name' => 'add_margin',
			'prefix' => '',
			'type' => 'number',
			'instructions' => 'Will not effected in single portfolio page',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5562d2f114913',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => 100,
			'placeholder' => 0,
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'kedavra-portfolio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));
/*
register_field_group(array (
	'key' => 'group_5563ee8a15433',
	'title' => 'Post Background',
	'fields' => array (
		array (
			'key' => 'field_5563ee936a184',
			'label' => 'Single Post Background',
			'name' => 'single_post_background',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));*/

register_field_group(array (
	'key' => 'group_550b61a487d04',
	'title' => 'Testimonial',
	'fields' => array (
		array (
			'key' => 'field_54f403ae2be8b',
			'label' => 'Testimonial Job',
			'name' => 'testimonial_job',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Add author job (function, job, etc) here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'kedavra_testimonial',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_556549556f92b',
	'title' => 'Portfolio Option',
	'fields' => array (
		array (
			'key' => 'field_55654a5aed29t',
			'label' => 'Custom Link',
			'name' => 'custom_link',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5565495fed296',
			'label' => 'Single Portfolio Type',
			'name' => 'portfolio_type',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'photography' => 'Light Box Single',
				'causes' => 'With Causes Detail and Sidebar',
				'agency' => 'With Project Detail',
				'architect' => 'With Project Detail and Fullwidth Image',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'photography',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_55654a5aed299',
			'label' => 'Raised Value',
			'name' => 'raised_value',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'causes',
					),
				),
			),
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55654a84ed29a',
			'label' => 'Donor Value',
			'name' => 'donor_value',
			'prefix' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'causes',
					),
				),
			),
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55654aaeed29b',
			'label' => 'Goal Value',
			'name' => 'goal_value',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'causes',
					),
				),
			),
			'wrapper' => array (
				'width' => 33,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_556579ed3cc4e',
			'label' => 'Goal Percentage',
			'name' => 'goal_percentage',
			'prefix' => '',
			'type' => 'number',
			'instructions' => 'Fill a percentage bar from 0-100%',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'causes',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '%',
			'min' => '',
			'max' => '',
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55657a7e3cc50',
			'label' => 'Donate Button',
			'name' => 'donate_button',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'causes',
					),
				),
			),
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55657a673cc4f',
			'label' => 'Donate Link',
			'name' => 'donate_link',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'causes',
					),
				),
			),
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5565565ab006c',
			'label' => 'Portfolio Width',
			'name' => 'portfolio_width',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => 'Choice for wide of small item',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'agency',
					),
				),
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'architect',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'wide-portfolio' => 'Wide Item',
				'standard' => 'Standard Item',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'standard',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_55657addbc8d7',
			'label' => 'Client Name',
			'name' => 'client_name',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'agency',
					),
				),
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'architect',
					),
				),
			),
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55657af6bc8d8',
			'label' => 'Release Date',
			'name' => 'release_date',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'agency',
					),
				),
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'architect',
					),
				),
			),
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55657b0abc8d9',
			'label' => 'Website Name',
			'name' => 'website_name',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'agency',
					),
				),
				array (
					array (
						'field' => 'field_5565495fed296',
						'operator' => '==',
						'value' => 'architect',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => 'http://',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'kedavra-portfolio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_550b61a481a26',
	'title' => 'Team',
	'fields' => array (
		array (
			'key' => 'field_54f3fe4f4680c',
			'label' => 'Team Function',
			'name' => 'team_function',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Add author job (function, job, etc) here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54f3ff440880d',
			'label' => 'Facebook',
			'name' => 'facebook',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'insert your Facebook Url here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54f400910880e',
			'label' => 'Twitter',
			'name' => 'twitter',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Insert your twitter Url here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54f400e70880f',
			'label' => 'Dribble',
			'name' => 'dribble',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Insert your dribbble Url here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54f4020308810',
			'label' => 'Instagram',
			'name' => 'instagram',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Insert your instagram Url here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5566873172b0f',
			'label' => 'Behance',
			'name' => 'behance',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Insert your Behance Url here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55668786255e9',
			'label' => 'Google Plus',
			'name' => 'google_plus',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Insert your Google+ Url here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'kedavra_team',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

register_field_group(array (
	'key' => 'group_557166a639df1',
	'title' => 'Hide Footer',
	'fields' => array (
		array (
			'key' => 'field_557166b34e939',
			'label' => 'Hide Footer',
			'name' => 'hide_footer',
			'prefix' => '',
			'type' => 'true_false',
			'instructions' => 'Hide footer for page builder template',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template/contact-template.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;